# Generated by Django 3.0.8 on 2020-07-13 05:45

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_auto_20200713_0545'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('is_granted', models.BooleanField(default=True, null=True)),
                ('channel_created_date_time', models.DateTimeField(default=datetime.datetime(2020, 7, 13, 5, 45, 37, 457804), null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=65535, null=True)),
                ('main_content_text', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt', 'docx'])])),
                ('main_content_audio', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'mp4', 'm4a', 'wma'])])),
                ('main_content_image', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('main_content_gif', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gif'])])),
                ('main_content_video', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'm4a', 'm4v', 'f4v', 'f4a', 'm4b', 'm4r', 'f4b', 'mov'])])),
                ('main_content_text_link', models.URLField(blank=True, null=True)),
                ('main_content_audio_link', models.URLField(blank=True, null=True)),
                ('main_content_image_link', models.URLField(blank=True, max_length=65535, null=True)),
                ('main_content_gif_link', models.URLField(blank=True, null=True)),
                ('main_content_video_link', models.URLField(blank=True, null=True)),
                ('no_of_likes', models.IntegerField(default=0)),
                ('no_of_shares', models.IntegerField(default=0)),
                ('no_of_comments', models.IntegerField(default=0)),
                ('no_of_reports', models.IntegerField(default=0)),
                ('post_created_date_time', models.DateTimeField(default=datetime.datetime(2020, 7, 13, 5, 45, 37, 458489), null=True)),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Channels')),
            ],
            options={
                'ordering': ['-post_created_date_time'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=1000, null=True)),
                ('no_of_reports', models.IntegerField(default=0, null=True)),
                ('comment_created_date_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Posts')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Posts')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
            options={
                'unique_together': {('profile', 'post')},
            },
        ),
    ]
