# Generated by Django 3.0.8 on 2020-08-29 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='channel_created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 29, 3, 55, 9, 644177), null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 29, 3, 55, 9, 646836), null=True),
        ),
    ]
