# Generated by Django 3.0.8 on 2020-08-30 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200830_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='channel_created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 3, 59, 54, 68676), null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 3, 59, 54, 69388), null=True),
        ),
    ]
