# Generated by Django 3.0.8 on 2020-07-13 05:44

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.PositiveIntegerField(default=21, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)])),
                ('image', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('is_phone_number_verified', models.BooleanField(default=False, null=True)),
                ('is_email_verified', models.BooleanField(default=False, null=True)),
                ('is_regular', models.BooleanField(default=False, null=True)),
                ('no_of_times_app_started', models.IntegerField(default=0, null=True)),
                ('account_created_date', models.DateTimeField(default=datetime.datetime(2020, 7, 13, 5, 44, 34, 32105), null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OTPCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField(default=479213, null=True)),
                ('time_when_otp_sent', models.DateTimeField(default=datetime.datetime(2020, 7, 13, 5, 44, 34, 32626), null=True)),
                ('profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
        ),
    ]
