# Generated by Django 3.0.8 on 2020-07-13 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200713_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcache',
            name='otp',
            field=models.IntegerField(default=839042, null=True),
        ),
        migrations.AlterField(
            model_name='otpcache',
            name='time_when_otp_sent',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 5, 45, 37, 452329), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 5, 45, 37, 451821), null=True),
        ),
    ]
