# Generated by Django 3.0.8 on 2020-08-29 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200713_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcache',
            name='otp',
            field=models.IntegerField(default=127602, null=True),
        ),
        migrations.AlterField(
            model_name='otpcache',
            name='time_when_otp_sent',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 29, 3, 55, 9, 624954), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 29, 3, 55, 9, 624003), null=True),
        ),
    ]
