# Generated by Django 3.0.8 on 2020-08-30 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200829_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcache',
            name='otp',
            field=models.IntegerField(default=674034, null=True),
        ),
        migrations.AlterField(
            model_name='otpcache',
            name='time_when_otp_sent',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 3, 44, 27, 392115), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 3, 44, 27, 391651), null=True),
        ),
    ]
