# Generated by Django 3.0.8 on 2020-08-30 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200830_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcache',
            name='otp',
            field=models.IntegerField(default=795466, null=True),
        ),
        migrations.AlterField(
            model_name='otpcache',
            name='time_when_otp_sent',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 3, 59, 54, 63611), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 3, 59, 54, 63024), null=True),
        ),
    ]
