# Generated by Django 3.0.8 on 2020-08-29 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 29, 3, 55, 9, 628057), null=True),
        ),
        migrations.AlterField(
            model_name='recordcomments',
            name='comment_created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 29, 3, 55, 9, 630194), null=True),
        ),
    ]
