# Generated by Django 3.0.8 on 2020-08-30 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20200829_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 3, 44, 27, 393718), null=True),
        ),
        migrations.AlterField(
            model_name='recordcomments',
            name='comment_created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 3, 44, 27, 394712), null=True),
        ),
    ]
