# Generated by Django 3.0.8 on 2020-08-30 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20200830_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 3, 59, 54, 65340), null=True),
        ),
        migrations.AlterField(
            model_name='recordcomments',
            name='comment_created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 3, 59, 54, 66474), null=True),
        ),
    ]
